# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7684c0046e8198103d50eaac560fac6e0fc245acabba5bcc90b3befaef618047757b5ed4bdc952b2ad04638c757c04d506fe578a27f6a6cb227ada1b0cd4a05b

test:
  secret_key_base: e43ceb4d13629f4f23b4bc269aa9ceb64c28f8ee16c1bf2bf0ab789d2a427dc5860ea0bd4e51ace1d14bc55bf40cf254e0ba56484ac7600e0aa2312fb8b0de73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
